baseURL = "https://bkkcast.me/"
languageCode = "jp"
title = "bkkcast"
hasCJKLanguage = true

[params]
  author = "bkkcast"
  description = "バンコクを中心として、海外で働くエンジニアを集めて、生活事情、最近エンジニア界隈で話題になったニュースなどについて話し合います"
  eyecatch = "img/eyecatch.png"

[menu]

  [[menu.main]]
    identifier = "twitter"
    name = "@bkkcast"
    url = "https://twitter.com/bkkcast"
    weight = -110

[social]
  twitter = "bkkcast"

[outputs]
  home = [ "HTML", "RSS"]

[outputFormats]
[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"
